import { createId } from '@tuwaio/shared/cuid';
import type { CollectionConfig } from 'payload';

import { isMemberOfOrganization } from '@/lib/access';

/**
 * End-user invoices generated by Payments-kind apps.
 * Tenant-isolated: every record scoped to an organization.
 * Immutable, and machine-authored: no manual creates, updates or deletes.
 */
export const AppInvoices: CollectionConfig = {
  slug: 'app-invoices',
  disableDuplicate: true,
  admin: {
    group: 'Payments',
    useAsTitle: 'id',
    defaultColumns: ['organization', 'app', 'status', 'totalAmount', 'currency', 'createdAt'],
    description:
      'Future feature (Payments App), still under active development and not available in any edition yet. Invoices ' +
      'are meant to be issued by the payment flow, which has not shipped — so creating, editing or deleting them by ' +
      'hand is disabled: a row here would claim money is owed against a collection process that does not exist.',
  },
  access: {
    read: isMemberOfOrganization,
    // An invoice is a financial record: it is generated by a Payments-kind app
    // against a real charge, never typed in. The REST surface that lists them
    // (`/api/v1/organizations/[orgId]/apps/[appId]/invoices`) runs with
    // `overrideAccess: true` and does its own org-scoped authorization, so
    // closing this gate does not touch the API — it only removes the admin's
    // "Create new" button, which could otherwise mint an invoice that
    // corresponds to no payment.
    //
    // `update` and `delete` were already shut for the same reason; `create`
    // being open was the gap.
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  fields: [
    {
      name: 'id',
      type: 'text',
      unique: true,
      required: true,
      defaultValue: () => createId(),
    },
    {
      name: 'app',
      type: 'relationship',
      relationTo: 'apps',
      required: true,
      index: true,
    },
    {
      name: 'organization',
      type: 'relationship',
      relationTo: 'organizations',
      required: true,
      index: true,
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Pending', value: 'pending' },
        { label: 'Paid', value: 'paid' },
        { label: 'Failed', value: 'failed' },
        { label: 'Expired', value: 'expired' },
        { label: 'Cancelled', value: 'cancelled' },
      ],
      index: true,
    },
    {
      name: 'baseAmount',
      type: 'number',
      required: true,
      admin: {
        description: 'Original fiat value before any markup or discount.',
      },
    },
    {
      name: 'totalAmount',
      type: 'number',
      required: true,
      admin: {
        description: 'Final fiat amount the end-user pays (baseAmount + markup - discount).',
      },
    },
    {
      name: 'currency',
      type: 'select',
      required: true,
      defaultValue: 'USD',
      options: [{ label: 'USD', value: 'USD' }],
    },
    {
      name: 'cryptoAmountExpected',
      type: 'text',
      required: true,
      admin: {
        description: 'Exact crypto amount expected (string to avoid JS float precision loss).',
      },
    },
    {
      name: 'acceptedPayment',
      type: 'relationship',
      relationTo: 'app-accepted-payments',
      required: true,
      admin: {
        description: 'Records exactly which token/chain/wallet was selected for this payment.',
      },
    },
    {
      name: 'txHash',
      type: 'text',
      index: true,
      // One on-chain payment settles one invoice. Enforced in the database,
      // not only here: the engine writes this column straight through Drizzle
      // (router.service.ts). NULLs stay distinct, so unpaid invoices are not
      // affected. It lived in a hand-written migration until the 2026-09-09
      // squash dropped it; the config is the source of truth now.
      unique: true,
      admin: {
        description: 'Populated by the tracking system once the on-chain transaction is detected.',
      },
    },
    {
      name: 'originWallet',
      type: 'text',
      admin: {
        description: 'The client wallet address that initiated the on-chain payment.',
      },
      validate: (value: unknown) => {
        if (!value) return true; // Optional field
        if (typeof value !== 'string') return 'Must be a string.';
        if (!/^0x[a-fA-F0-9]+$/.test(value)) {
          return 'Must be a valid hex address starting with 0x.';
        }
        return true;
      },
    },
    {
      name: 'metadata',
      type: 'json',
      validate: () => true,
      admin: {
        description: 'Custom customer/order data attached by the merchant app.',
      },
    },
  ],
};
