/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    transactions: Transaction;
    apps: App;
    'quota-usage-ledger': QuotaUsageLedger;
    organizations: Organization;
    'organization-members': OrganizationMember;
    'deleted-accounts': DeletedAccount;
    'deleted-organizations': DeletedOrganization;
    'deleted-organization-members': DeletedOrganizationMember;
    'webhook-endpoints': WebhookEndpoint;
    'webhook-deliveries': WebhookDelivery;
    outbox_events: OutboxEvent;
    'app-accepted-payments': AppAcceptedPayment;
    'app-invoices': AppInvoice;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    apps: AppsSelect<false> | AppsSelect<true>;
    'quota-usage-ledger': QuotaUsageLedgerSelect<false> | QuotaUsageLedgerSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'organization-members': OrganizationMembersSelect<false> | OrganizationMembersSelect<true>;
    'deleted-accounts': DeletedAccountsSelect<false> | DeletedAccountsSelect<true>;
    'deleted-organizations': DeletedOrganizationsSelect<false> | DeletedOrganizationsSelect<true>;
    'deleted-organization-members': DeletedOrganizationMembersSelect<false> | DeletedOrganizationMembersSelect<true>;
    'webhook-endpoints': WebhookEndpointsSelect<false> | WebhookEndpointsSelect<true>;
    'webhook-deliveries': WebhookDeliveriesSelect<false> | WebhookDeliveriesSelect<true>;
    outbox_events: OutboxEventsSelect<false> | OutboxEventsSelect<true>;
    'app-accepted-payments': AppAcceptedPaymentsSelect<false> | AppAcceptedPaymentsSelect<true>;
    'app-invoices': AppInvoicesSelect<false> | AppInvoicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This node runs on a single administrator account — the one created by the seed. Creating users is disabled: there is no sign-up form, no verification email and no password reset in this edition, so a second account would be unrecoverable the moment its password was lost. Change the email or password of the existing account instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  telegramUsername?: string | null;
  discordUsername?: string | null;
  /**
   * Managed via the TOTP setup flow below - the checkbox itself is display-only.
   */
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  backupCode?: string | null;
  roles: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Ledger of tracked transactions, written by the engine. Records are not created, edited or deleted from here — they mirror on-chain history and the quota that was spent tracking it. Rows leave only with the app or the organization they belong to.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Tenant Owner (Auto-stamped via API Key)
   */
  owner: string | Organization;
  /**
   * The App used to initiate this transaction.
   */
  app?: (string | null) | App;
  /**
   * App name for filtering by apps.
   */
  appName: string;
  txKey: string;
  chainId: string;
  from: string;
  type: string;
  connectorType: string;
  adapter: 'evm' | 'solana' | 'starknet';
  /**
   * Tracking System
   */
  tracker: 'ethereum' | 'safe' | 'gelato' | 'solana' | 'erc4337';
  status?: ('Failed' | 'Success' | 'Replaced') | null;
  /**
   * Engine sync status
   */
  syncStatus?: ('synced' | 'pending-sync') | null;
  pending: boolean;
  isError?: boolean | null;
  localTimestamp: number;
  finishedTimestamp?: number | null;
  title?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  description?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  confirmations?: string | null;
  requiredConfirmations?: number | null;
  rpcUrl?: string | null;
  /**
   * Linked AppInvoice (Payments apps only).
   */
  appInvoiceId?: (string | null) | AppInvoice;
  /**
   * AML screening result (Payments apps only).
   */
  amlStatus?: ('not_applicable' | 'pending' | 'passed' | 'flagged' | 'failed') | null;
  /**
   * Risk score from AML provider (0-100).
   */
  amlRiskScore?: number | null;
  /**
   * Raw response data from the AML provider.
   */
  amlProviderData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  hash?: string | null;
  to?: string | null;
  value?: string | null;
  input?: string | null;
  nonce?: number | null;
  maxFeePerGas?: string | null;
  maxPriorityFeePerGas?: string | null;
  replacedTxHash?: string | null;
  bundlerUrl?: string | null;
  pimlicoApiKey?: string | null;
  fee?: number | null;
  slot?: number | null;
  recentBlockhash?: string | null;
  instructions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  actualFee?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contractAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Workspaces that group apps under one quota balance and one RPS limit. The first is created together with the administrator account, and the administrator owns every organization created here. Quota and RPS are anti-runaway guard rails on this node, not billing: new organizations get the Community Edition limits, which are effectively unlimited and never expire. Deleting an organization removes its members, apps and transactions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  name: string;
  slug?: string | null;
  createdBy: string;
  /**
   * Available transaction quota for this organization.
   */
  quotaBalance: number;
  /**
   * Global active requests per second (RPS) limit for all apps in this organization.
   */
  rpsLimit: number;
  /**
   * Maximum requests per second (RPS) limit the organization has paid for.
   */
  rpsPaidLimit: number;
  /**
   * Unused in Community Edition: RPS never expires (rpsForever), and the expiration cron is not part of this edition.
   */
  rpsExpiresAt?: string | null;
  /**
   * Total quota consumed this billing cycle. Synced from Redis.
   */
  quotaUsed: number;
  /**
   * If enabled, the RPS limit for this organization will never expire or reset.
   */
  rpsForever?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * An app is one integration of an organization with the engine: it owns the API key pair (pk_/sk_) the SDK signs requests with, the IP/domain whitelists, and optional bring-your-own RPC keys. Transactions and webhook endpoints hang off an app, and deleting it removes them too. Environment sets the quota price per tracked transaction (test costs half of live) and, at creation, the key prefix. Up to 30 apps per organization.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps".
 */
export interface App {
  /**
   * Master switch. While this is off the engine rejects every request signed with this app’s keys (HTTP 403 “App is disabled”): no transactions are tracked and no webhooks are dispatched. Existing data is kept untouched.
   */
  isActive?: boolean | null;
  id: string;
  name: string;
  organization: string | Organization;
  environment: 'live' | 'test';
  /**
   * Determines the feature set enabled for this app.
   */
  kind: 'basic' | 'payments';
  /**
   * Safe to share (pk_live_...). Used for client-side identification.
   */
  publicKey?: string | null;
  /**
   * CRITICAL: sk_live_... Reveal via password + 2FA step-up below.
   */
  secretKey?: string | null;
  secretKeyHash?: string | null;
  /**
   * Allow requests only from these IP addresses. Leave empty to allow all.
   */
  ipWhitelist?:
    | {
        ip: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Allow requests only from these domains/origins. Leave empty to allow all.
   */
  domainsWhitelist?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  rpcConfigs?:
    | {
        chainId: string;
        rpcUrl: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Bring your own Alchemy key for this specific app.
   */
  alchemyApiKey?: string | null;
  /**
   * Optional. URL or token. Applied if Alchemy is not configured. A bare token also requires QuickNode App Name below — the endpoint URL is built from the two together.
   */
  quickNodeApiKey?: string | null;
  /**
   * Required once a QuickNode API Key is set. The subdomain of your QuickNode endpoint — for https://my-app.quiknode.pro/<token>/ this is "my-app".
   */
  quickNodeAppName?: string | null;
  /**
   * Optional. Used for Gelato relay tracking.
   */
  gelatoApiKey?: string | null;
  /**
   * Optional. Used for Pimlico ERC-4337 bundler and paymaster tracking.
   */
  pimlicoApiKey?: string | null;
  /**
   * Configuration for the Payments app kind.
   */
  paymentSettings?: {
    /**
     * If enabled, incoming payment transactions will be screened via GoPlus Labs.
     */
    amlEnabled?: boolean | null;
    /**
     * Optional. Your own GoPlus Labs API Key. If blank, the system fallback key is used (+5 quota/tx).
     */
    goPlusApiKey?: string | null;
    /**
     * Optional. Your own GoPlus Labs API Secret.
     */
    goPlusApiSecret?: string | null;
    /**
     * PDF template configuration for @pdfme/generator.
     */
    appInvoiceTemplate?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Future feature (Payments App), still under active development and not available in any edition yet. Invoices are meant to be issued by the payment flow, which has not shipped — so creating, editing or deleting them by hand is disabled: a row here would claim money is owed against a collection process that does not exist.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-invoices".
 */
export interface AppInvoice {
  id: string;
  app: string | App;
  organization: string | Organization;
  status: 'draft' | 'pending' | 'paid' | 'failed' | 'expired' | 'cancelled';
  /**
   * Original fiat value before any markup or discount.
   */
  baseAmount: number;
  /**
   * Final fiat amount the end-user pays (baseAmount + markup - discount).
   */
  totalAmount: number;
  currency: 'USD';
  /**
   * Exact crypto amount expected (string to avoid JS float precision loss).
   */
  cryptoAmountExpected: string;
  /**
   * Records exactly which token/chain/wallet was selected for this payment.
   */
  acceptedPayment: string | AppAcceptedPayment;
  /**
   * Populated by the tracking system once the on-chain transaction is detected.
   */
  txHash?: string | null;
  /**
   * The client wallet address that initiated the on-chain payment.
   */
  originWallet?: string | null;
  /**
   * Custom customer/order data attached by the merchant app.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Future feature (Payments App). Creation is disabled in every edition until the payment flow ships; existing records stay editable so a configuration can be corrected.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-accepted-payments".
 */
export interface AppAcceptedPayment {
  id: string;
  app: string | App;
  organization: string | Organization;
  /**
   * e.g., "USDC on Base", "Native ETH on Mainnet"
   */
  name: string;
  /**
   * The destination wallet address (Hex string) that will receive direct transfers.
   */
  walletAddressToReceivePayment: string;
  /**
   * Hex string of the ERC20 token, or strictly "native" for ETH/SOL.
   */
  tokenAddress: string;
  chainId: number;
  /**
   * e.g., "USDC", "ETH"
   */
  symbol: string;
  decimals: number;
  /**
   * Percentage markup added to this payment method (e.g. 1.5 for 1.5%).
   */
  markup?: number | null;
  /**
   * Percentage discount subtracted from this payment method (e.g. 1.0 for 1.0%).
   */
  discount?: number | null;
  /**
   * Chainlink Price Feed aggregator address (Hex string) for USD exchange rate conversions on-chain.
   */
  priceFeedAddress: string;
  /**
   * Toggle to enable/disable this payment method.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only record of quota drained from each organization, flushed from Redis in batches by the engine. Fully read-only: an entry is the reconciliation trail between what the engine metered and what the balance says, and a ledger anyone can write to cannot reconcile anything.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quota-usage-ledger".
 */
export interface QuotaUsageLedger {
  id: string;
  organization: string | Organization;
  batchId: string;
  amount: number;
  usageCategory: string;
  sourceWindow: string;
  contentDigest: string;
  status: 'applied' | 'manual-review';
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only in Community Edition. An organization here has exactly one member: the single administrator who created it, added automatically as owner. Membership cannot be granted or revoked because this edition has no second account to grant it to — no sign-up, no invitations, no email.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-members".
 */
export interface OrganizationMember {
  id: string;
  organization: string | Organization;
  user: string | User;
  role: 'owner' | 'admin' | 'member';
  updatedAt: string;
  createdAt: string;
}
/**
 * Tombstones written automatically when an account is deleted. Creation and editing are disabled: a row here is proof that a specific deletion happened, and a hand-written or hand-edited one proves nothing. Clearing old entries stays available to global admins.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deleted-accounts".
 */
export interface DeletedAccount {
  id: string;
  email: string;
  /**
   * The ID of the User before deletion
   */
  originalId: string;
  deletedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tombstones written automatically when an organization is deleted, including who deleted it. Creation and editing are disabled — this is the only surviving trace of an organization and everything it owned, so it must not be something a person can compose. Clearing old entries stays available to global admins.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deleted-organizations".
 */
export interface DeletedOrganization {
  id: string;
  orgName: string;
  /**
   * The ID of the Organization before deletion
   */
  originalId: string;
  /**
   * User ID who performed the deletion
   */
  deletedBy: string;
  deletedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tombstones written automatically when a membership is revoked — the record of who lost access to which organization and when. Creation and editing are disabled so the trail cannot be authored after the fact; clearing old entries stays available to global admins.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deleted-organization-members".
 */
export interface DeletedOrganizationMember {
  id: string;
  organization: string;
  user?: string | null;
  email: string;
  deletedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * URLs the engine POSTs to when a tracked transaction of an app changes state. Each endpoint gets its own auto-generated signing secret, so the receiver can verify the payload came from Quasar. Every delivery attempt costs quota and is logged under Webhook Deliveries. Production requires HTTPS; one localhost endpoint per organization is allowed for local development.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints".
 */
export interface WebhookEndpoint {
  /**
   * Inactive endpoints are skipped by the dispatcher: no deliveries, no retries, no quota spent.
   */
  isActive?: boolean | null;
  id: string;
  /**
   * The App (tenant environment) this webhook endpoint belongs to.
   */
  app: string | App;
  /**
   * The destination URL for webhook delivery. HTTPS required in production, except for single local development endpoint (localhost).
   */
  url: string;
  /**
   * HMAC signing secret (whsec_...). Auto-generated on creation. Reveal via password + 2FA step-up below.
   */
  signingSecret: string;
  /**
   * Events that trigger delivery to this endpoint. Use "*" to subscribe to all.
   */
  events: ('*' | 'transaction:success' | 'transaction:failed' | 'transaction:replaced')[];
  /**
   * Not available in Community Edition.
   */
  isSystemWebhook?: boolean | null;
  /**
   * Optional human-readable label for this endpoint.
   */
  description?: string | null;
  /**
   * Which transaction types reach this endpoint. Use * for all of them, or an exact type string — the same value the SDK sends as `type` on the transaction (e.g. "transfer"). Matching is exact, not a pattern.
   */
  txType: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only delivery log, written by the dispatcher. Records cannot be created, edited or deleted here — a delivery attempt is evidence of what the system actually sent, and evidence that can be edited away is worth nothing during an incident. Retry appears only on failed deliveries and records the new attempt on the same row.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries".
 */
export interface WebhookDelivery {
  id: string;
  /**
   * The webhook endpoint this delivery was dispatched to.
   */
  endpoint: string | WebhookEndpoint;
  /**
   * The type of event that triggered this delivery (e.g., tx.confirmed).
   */
  eventType: string;
  /**
   * The hash or unique ID of the transaction that triggered this webhook.
   */
  txKey: string;
  /**
   * HTTP status code returned by the client server (e.g., 200, 500).
   */
  httpStatus?: number | null;
  /**
   * True if httpStatus is in the 2xx range.
   */
  success: boolean;
  /**
   * The exact JSON body sent to the endpoint.
   */
  requestPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Response from the server. Can be HTML or JSON text.
   */
  responseBody?: string | null;
  /**
   * Round-trip time of the HTTP request in milliseconds.
   */
  executionTimeMs?: number | null;
  /**
   * The number of attempts made to deliver this webhook.
   */
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Transactional outbox: events the system committed alongside the data that produced them, waiting to be relayed. Fully read-only — the whole guarantee of the pattern is that a row appears here only as part of the database transaction that caused it, so anything inserted or edited by hand is an event that never happened.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox_events".
 */
export interface OutboxEvent {
  id: number;
  eventType: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processed' | 'failed';
  attempts: number;
  nextAttemptAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'apps';
        value: string | App;
      } | null)
    | ({
        relationTo: 'quota-usage-ledger';
        value: string | QuotaUsageLedger;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'organization-members';
        value: string | OrganizationMember;
      } | null)
    | ({
        relationTo: 'deleted-accounts';
        value: string | DeletedAccount;
      } | null)
    | ({
        relationTo: 'deleted-organizations';
        value: string | DeletedOrganization;
      } | null)
    | ({
        relationTo: 'deleted-organization-members';
        value: string | DeletedOrganizationMember;
      } | null)
    | ({
        relationTo: 'webhook-endpoints';
        value: string | WebhookEndpoint;
      } | null)
    | ({
        relationTo: 'webhook-deliveries';
        value: string | WebhookDelivery;
      } | null)
    | ({
        relationTo: 'outbox_events';
        value: number | OutboxEvent;
      } | null)
    | ({
        relationTo: 'app-accepted-payments';
        value: string | AppAcceptedPayment;
      } | null)
    | ({
        relationTo: 'app-invoices';
        value: string | AppInvoice;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  telegramUsername?: T;
  discordUsername?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  backupCode?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  owner?: T;
  app?: T;
  appName?: T;
  txKey?: T;
  chainId?: T;
  from?: T;
  type?: T;
  connectorType?: T;
  adapter?: T;
  tracker?: T;
  status?: T;
  syncStatus?: T;
  pending?: T;
  isError?: T;
  localTimestamp?: T;
  finishedTimestamp?: T;
  title?: T;
  description?: T;
  error?: T;
  payload?: T;
  confirmations?: T;
  requiredConfirmations?: T;
  rpcUrl?: T;
  appInvoiceId?: T;
  amlStatus?: T;
  amlRiskScore?: T;
  amlProviderData?: T;
  hash?: T;
  to?: T;
  value?: T;
  input?: T;
  nonce?: T;
  maxFeePerGas?: T;
  maxPriorityFeePerGas?: T;
  replacedTxHash?: T;
  bundlerUrl?: T;
  pimlicoApiKey?: T;
  fee?: T;
  slot?: T;
  recentBlockhash?: T;
  instructions?: T;
  actualFee?: T;
  contractAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps_select".
 */
export interface AppsSelect<T extends boolean = true> {
  isActive?: T;
  id?: T;
  name?: T;
  organization?: T;
  environment?: T;
  kind?: T;
  publicKey?: T;
  secretKey?: T;
  secretKeyHash?: T;
  ipWhitelist?:
    | T
    | {
        ip?: T;
        id?: T;
      };
  domainsWhitelist?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  rpcConfigs?:
    | T
    | {
        chainId?: T;
        rpcUrl?: T;
        id?: T;
      };
  alchemyApiKey?: T;
  quickNodeApiKey?: T;
  quickNodeAppName?: T;
  gelatoApiKey?: T;
  pimlicoApiKey?: T;
  paymentSettings?:
    | T
    | {
        amlEnabled?: T;
        goPlusApiKey?: T;
        goPlusApiSecret?: T;
        appInvoiceTemplate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quota-usage-ledger_select".
 */
export interface QuotaUsageLedgerSelect<T extends boolean = true> {
  id?: T;
  organization?: T;
  batchId?: T;
  amount?: T;
  usageCategory?: T;
  sourceWindow?: T;
  contentDigest?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  createdBy?: T;
  quotaBalance?: T;
  rpsLimit?: T;
  rpsPaidLimit?: T;
  rpsExpiresAt?: T;
  quotaUsed?: T;
  rpsForever?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-members_select".
 */
export interface OrganizationMembersSelect<T extends boolean = true> {
  id?: T;
  organization?: T;
  user?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deleted-accounts_select".
 */
export interface DeletedAccountsSelect<T extends boolean = true> {
  id?: T;
  email?: T;
  originalId?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deleted-organizations_select".
 */
export interface DeletedOrganizationsSelect<T extends boolean = true> {
  id?: T;
  orgName?: T;
  originalId?: T;
  deletedBy?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deleted-organization-members_select".
 */
export interface DeletedOrganizationMembersSelect<T extends boolean = true> {
  id?: T;
  organization?: T;
  user?: T;
  email?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-endpoints_select".
 */
export interface WebhookEndpointsSelect<T extends boolean = true> {
  isActive?: T;
  id?: T;
  app?: T;
  url?: T;
  signingSecret?: T;
  events?: T;
  isSystemWebhook?: T;
  description?: T;
  txType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries_select".
 */
export interface WebhookDeliveriesSelect<T extends boolean = true> {
  id?: T;
  endpoint?: T;
  eventType?: T;
  txKey?: T;
  httpStatus?: T;
  success?: T;
  requestPayload?: T;
  responseBody?: T;
  executionTimeMs?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox_events_select".
 */
export interface OutboxEventsSelect<T extends boolean = true> {
  eventType?: T;
  payload?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-accepted-payments_select".
 */
export interface AppAcceptedPaymentsSelect<T extends boolean = true> {
  id?: T;
  app?: T;
  organization?: T;
  name?: T;
  walletAddressToReceivePayment?: T;
  tokenAddress?: T;
  chainId?: T;
  symbol?: T;
  decimals?: T;
  markup?: T;
  discount?: T;
  priceFeedAddress?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-invoices_select".
 */
export interface AppInvoicesSelect<T extends boolean = true> {
  id?: T;
  app?: T;
  organization?: T;
  status?: T;
  baseAmount?: T;
  totalAmount?: T;
  currency?: T;
  cryptoAmountExpected?: T;
  acceptedPayment?: T;
  txHash?: T;
  originWallet?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}