/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres';
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  timestamp,
  boolean,
  numeric,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core';
import { relations } from '@payloadcms/db-postgres/drizzle';
export const enum_users_roles = pgEnum('enum_users_roles', ['admin', 'user']);
export const enum_transactions_adapter = pgEnum('enum_transactions_adapter', ['evm', 'solana', 'starknet']);
export const enum_transactions_tracker = pgEnum('enum_transactions_tracker', [
  'ethereum',
  'safe',
  'gelato',
  'solana',
  'erc4337',
]);
export const enum_transactions_status = pgEnum('enum_transactions_status', ['Failed', 'Success', 'Replaced']);
export const enum_transactions_sync_status = pgEnum('enum_transactions_sync_status', ['synced', 'pending-sync']);
export const enum_transactions_aml_status = pgEnum('enum_transactions_aml_status', [
  'not_applicable',
  'pending',
  'passed',
  'flagged',
  'failed',
]);
export const enum_apps_environment = pgEnum('enum_apps_environment', ['live', 'test']);
export const enum_apps_kind = pgEnum('enum_apps_kind', ['basic', 'payments']);
export const enum_quota_usage_ledger_status = pgEnum('enum_quota_usage_ledger_status', ['applied', 'manual-review']);
export const enum_organization_members_role = pgEnum('enum_organization_members_role', ['owner', 'admin', 'member']);
export const enum_webhook_endpoints_events = pgEnum('enum_webhook_endpoints_events', [
  '*',
  'transaction:success',
  'transaction:failed',
  'transaction:replaced',
]);
export const enum_outbox_events_status = pgEnum('enum_outbox_events_status', ['pending', 'processed', 'failed']);
export const enum_app_invoices_status = pgEnum('enum_app_invoices_status', [
  'draft',
  'pending',
  'paid',
  'failed',
  'expired',
  'cancelled',
]);
export const enum_app_invoices_currency = pgEnum('enum_app_invoices_currency', ['USD']);

export const users_roles = pgTable(
  'users_roles',
  {
    order: integer('order').notNull(),
    parent: varchar('parent_id').notNull(),
    value: enum_users_roles('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('users_roles_order_idx').on(columns.order),
    index('users_roles_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_roles_parent_fk',
    }).onDelete('cascade'),
  ],
);

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const users = pgTable(
  'users',
  {
    id: varchar('id').primaryKey(),
    name: varchar('name'),
    telegramUsername: varchar('telegram_username'),
    discordUsername: varchar('discord_username'),
    twoFactorEnabled: boolean('two_factor_enabled').default(false),
    twoFactorSecret: varchar('two_factor_secret'),
    backupCode: varchar('backup_code'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
);

export const transactions = pgTable(
  'transactions',
  {
    id: serial('id').primaryKey(),
    owner: varchar('owner_id')
      .notNull()
      .references(() => organizations.id, {
        onDelete: 'set null',
      }),
    app: varchar('app_id').references(() => apps.id, {
      onDelete: 'set null',
    }),
    appName: varchar('app_name').notNull().default('Web3 App'),
    txKey: varchar('tx_key').notNull(),
    chainId: varchar('chain_id').notNull(),
    from: varchar('from').notNull(),
    type: varchar('type').notNull(),
    connectorType: varchar('connector_type').notNull(),
    adapter: enum_transactions_adapter('adapter').notNull(),
    tracker: enum_transactions_tracker('tracker').notNull(),
    status: enum_transactions_status('status'),
    syncStatus: enum_transactions_sync_status('sync_status').default('synced'),
    pending: boolean('pending').notNull().default(true),
    isError: boolean('is_error').default(false),
    localTimestamp: numeric('local_timestamp', { mode: 'number' }).notNull(),
    finishedTimestamp: numeric('finished_timestamp', { mode: 'number' }),
    title: jsonb('title'),
    description: jsonb('description'),
    error: jsonb('error'),
    payload: jsonb('payload'),
    confirmations: varchar('confirmations'),
    requiredConfirmations: numeric('required_confirmations', { mode: 'number' }),
    rpcUrl: varchar('rpc_url'),
    appInvoiceId: varchar('app_invoice_id_id').references(() => app_invoices.id, {
      onDelete: 'set null',
    }),
    amlStatus: enum_transactions_aml_status('aml_status').default('not_applicable'),
    amlRiskScore: numeric('aml_risk_score', { mode: 'number' }).default(0),
    amlProviderData: jsonb('aml_provider_data'),
    hash: varchar('hash'),
    to: varchar('to'),
    value: varchar('value'),
    input: varchar('input'),
    nonce: numeric('nonce', { mode: 'number' }),
    maxFeePerGas: varchar('max_fee_per_gas'),
    maxPriorityFeePerGas: varchar('max_priority_fee_per_gas'),
    replacedTxHash: varchar('replaced_tx_hash'),
    bundlerUrl: varchar('bundler_url'),
    pimlicoApiKey: varchar('pimlico_api_key'),
    fee: numeric('fee', { mode: 'number' }),
    slot: numeric('slot', { mode: 'number' }),
    recentBlockhash: varchar('recent_blockhash'),
    instructions: jsonb('instructions'),
    actualFee: jsonb('actual_fee'),
    contractAddress: varchar('contract_address'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('transactions_owner_idx').on(columns.owner),
    index('transactions_app_idx').on(columns.app),
    index('transactions_app_name_idx').on(columns.appName),
    uniqueIndex('transactions_tx_key_idx').on(columns.txKey),
    index('transactions_chain_id_idx').on(columns.chainId),
    index('transactions_from_idx').on(columns.from),
    index('transactions_adapter_idx').on(columns.adapter),
    index('transactions_status_idx').on(columns.status),
    index('transactions_sync_status_idx').on(columns.syncStatus),
    index('transactions_local_timestamp_idx').on(columns.localTimestamp),
    index('transactions_app_invoice_id_idx').on(columns.appInvoiceId),
    index('transactions_aml_status_idx').on(columns.amlStatus),
    index('transactions_hash_idx').on(columns.hash),
    index('transactions_to_idx').on(columns.to),
    index('transactions_updated_at_idx').on(columns.updatedAt),
    index('transactions_created_at_idx').on(columns.createdAt),
  ],
);

export const apps_ip_whitelist = pgTable(
  'apps_ip_whitelist',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    ip: varchar('ip').notNull(),
  },
  (columns) => [
    index('apps_ip_whitelist_order_idx').on(columns._order),
    index('apps_ip_whitelist_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [apps.id],
      name: 'apps_ip_whitelist_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const apps_domains_whitelist = pgTable(
  'apps_domains_whitelist',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    domain: varchar('domain').notNull(),
  },
  (columns) => [
    index('apps_domains_whitelist_order_idx').on(columns._order),
    index('apps_domains_whitelist_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [apps.id],
      name: 'apps_domains_whitelist_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const apps_rpc_configs = pgTable(
  'apps_rpc_configs',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    chainId: varchar('chain_id').notNull(),
    rpcUrl: varchar('rpc_url').notNull(),
  },
  (columns) => [
    index('apps_rpc_configs_order_idx').on(columns._order),
    index('apps_rpc_configs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [apps.id],
      name: 'apps_rpc_configs_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const apps = pgTable(
  'apps',
  {
    id: varchar('id').primaryKey(),
    isActive: boolean('is_active').default(true),
    name: varchar('name').notNull(),
    organization: varchar('organization_id')
      .notNull()
      .references(() => organizations.id, {
        onDelete: 'set null',
      }),
    environment: enum_apps_environment('environment').notNull().default('test'),
    kind: enum_apps_kind('kind').notNull().default('basic'),
    publicKey: varchar('public_key'),
    secretKey: varchar('secret_key'),
    secretKeyHash: varchar('secret_key_hash'),
    alchemyApiKey: varchar('alchemy_api_key'),
    quickNodeApiKey: varchar('quick_node_api_key'),
    quickNodeAppName: varchar('quick_node_app_name'),
    gelatoApiKey: varchar('gelato_api_key'),
    pimlicoApiKey: varchar('pimlico_api_key'),
    paymentSettings_amlEnabled: boolean('payment_settings_aml_enabled').default(false),
    paymentSettings_goPlusApiKey: varchar('payment_settings_go_plus_api_key'),
    paymentSettings_goPlusApiSecret: varchar('payment_settings_go_plus_api_secret'),
    paymentSettings_appInvoiceTemplate: jsonb('payment_settings_app_invoice_template'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('apps_is_active_idx').on(columns.isActive),
    index('apps_organization_idx').on(columns.organization),
    index('apps_environment_idx').on(columns.environment),
    index('apps_kind_idx').on(columns.kind),
    uniqueIndex('apps_public_key_idx').on(columns.publicKey),
    uniqueIndex('apps_secret_key_idx').on(columns.secretKey),
    index('apps_secret_key_hash_idx').on(columns.secretKeyHash),
    index('apps_updated_at_idx').on(columns.updatedAt),
    index('apps_created_at_idx').on(columns.createdAt),
  ],
);

export const quota_usage_ledger = pgTable(
  'quota_usage_ledger',
  {
    id: varchar('id').primaryKey(),
    organization: varchar('organization_id')
      .notNull()
      .references(() => organizations.id, {
        onDelete: 'set null',
      }),
    batchId: varchar('batch_id').notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    usageCategory: varchar('usage_category').notNull(),
    sourceWindow: varchar('source_window').notNull(),
    contentDigest: varchar('content_digest').notNull(),
    status: enum_quota_usage_ledger_status('status').notNull().default('applied'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('quota_usage_ledger_organization_idx').on(columns.organization),
    uniqueIndex('quota_usage_ledger_batch_id_idx').on(columns.batchId),
    index('quota_usage_ledger_status_idx').on(columns.status),
    index('quota_usage_ledger_updated_at_idx').on(columns.updatedAt),
    index('quota_usage_ledger_created_at_idx').on(columns.createdAt),
  ],
);

export const organizations = pgTable(
  'organizations',
  {
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug'),
    createdBy: varchar('created_by').notNull(),
    quotaBalance: numeric('quota_balance', { mode: 'number' }).notNull().default(100000000),
    rpsLimit: numeric('rps_limit', { mode: 'number' }).notNull().default(100000),
    rpsPaidLimit: numeric('rps_paid_limit', { mode: 'number' }).notNull().default(100000),
    rpsExpiresAt: timestamp('rps_expires_at', { mode: 'string', withTimezone: true, precision: 3 }),
    quotaUsed: numeric('quota_used', { mode: 'number' }).notNull().default(0),
    rpsForever: boolean('rps_forever').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    uniqueIndex('organizations_slug_idx').on(columns.slug),
    index('organizations_created_by_idx').on(columns.createdBy),
    index('organizations_updated_at_idx').on(columns.updatedAt),
    index('organizations_created_at_idx').on(columns.createdAt),
  ],
);

export const organization_members = pgTable(
  'organization_members',
  {
    id: varchar('id').primaryKey(),
    organization: varchar('organization_id')
      .notNull()
      .references(() => organizations.id, {
        onDelete: 'set null',
      }),
    user: varchar('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    role: enum_organization_members_role('role').notNull().default('member'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('organization_members_organization_idx').on(columns.organization),
    index('organization_members_user_idx').on(columns.user),
    index('organization_members_updated_at_idx').on(columns.updatedAt),
    index('organization_members_created_at_idx').on(columns.createdAt),
    uniqueIndex('organization_user_idx').on(columns.organization, columns.user),
  ],
);

export const deleted_accounts = pgTable(
  'deleted_accounts',
  {
    id: varchar('id').primaryKey(),
    email: varchar('email').notNull(),
    originalId: varchar('original_id').notNull(),
    deletedAt: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('deleted_accounts_email_idx').on(columns.email),
    index('deleted_accounts_original_id_idx').on(columns.originalId),
    index('deleted_accounts_deleted_at_idx').on(columns.deletedAt),
    index('deleted_accounts_updated_at_idx').on(columns.updatedAt),
    index('deleted_accounts_created_at_idx').on(columns.createdAt),
  ],
);

export const deleted_organizations = pgTable(
  'deleted_organizations',
  {
    id: varchar('id').primaryKey(),
    orgName: varchar('org_name').notNull(),
    originalId: varchar('original_id').notNull(),
    deletedBy: varchar('deleted_by').notNull(),
    deletedAt: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('deleted_organizations_original_id_idx').on(columns.originalId),
    index('deleted_organizations_deleted_by_idx').on(columns.deletedBy),
    index('deleted_organizations_deleted_at_idx').on(columns.deletedAt),
    index('deleted_organizations_updated_at_idx').on(columns.updatedAt),
    index('deleted_organizations_created_at_idx').on(columns.createdAt),
  ],
);

export const deleted_organization_members = pgTable(
  'deleted_organization_members',
  {
    id: varchar('id').primaryKey(),
    organization: varchar('organization').notNull(),
    user: varchar('user'),
    email: varchar('email').notNull(),
    deletedAt: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('deleted_organization_members_organization_idx').on(columns.organization),
    index('deleted_organization_members_user_idx').on(columns.user),
    index('deleted_organization_members_email_idx').on(columns.email),
    index('deleted_organization_members_deleted_at_idx').on(columns.deletedAt),
    index('deleted_organization_members_updated_at_idx').on(columns.updatedAt),
    index('deleted_organization_members_created_at_idx').on(columns.createdAt),
  ],
);

export const webhook_endpoints_events = pgTable(
  'webhook_endpoints_events',
  {
    order: integer('order').notNull(),
    parent: varchar('parent_id').notNull(),
    value: enum_webhook_endpoints_events('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('webhook_endpoints_events_order_idx').on(columns.order),
    index('webhook_endpoints_events_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [webhook_endpoints.id],
      name: 'webhook_endpoints_events_parent_fk',
    }).onDelete('cascade'),
  ],
);

export const webhook_endpoints = pgTable(
  'webhook_endpoints',
  {
    id: varchar('id').primaryKey(),
    isActive: boolean('is_active').default(true),
    app: varchar('app_id')
      .notNull()
      .references(() => apps.id, {
        onDelete: 'set null',
      }),
    url: varchar('url').notNull(),
    signingSecret: varchar('signing_secret').notNull(),
    isSystemWebhook: boolean('is_system_webhook').default(false),
    description: varchar('description'),
    txType: varchar('tx_type').notNull().default('*'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('webhook_endpoints_app_idx').on(columns.app),
    uniqueIndex('webhook_endpoints_signing_secret_idx').on(columns.signingSecret),
    index('webhook_endpoints_updated_at_idx').on(columns.updatedAt),
    index('webhook_endpoints_created_at_idx').on(columns.createdAt),
  ],
);

export const webhook_deliveries = pgTable(
  'webhook_deliveries',
  {
    id: varchar('id').primaryKey(),
    endpoint: varchar('endpoint_id')
      .notNull()
      .references(() => webhook_endpoints.id, {
        onDelete: 'set null',
      }),
    eventType: varchar('event_type').notNull(),
    txKey: varchar('tx_key').notNull(),
    httpStatus: numeric('http_status', { mode: 'number' }),
    success: boolean('success').notNull().default(false),
    requestPayload: jsonb('request_payload'),
    responseBody: varchar('response_body'),
    executionTimeMs: numeric('execution_time_ms', { mode: 'number' }),
    attempts: numeric('attempts', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('webhook_deliveries_endpoint_idx').on(columns.endpoint),
    index('webhook_deliveries_event_type_idx').on(columns.eventType),
    index('webhook_deliveries_tx_key_idx').on(columns.txKey),
    index('webhook_deliveries_updated_at_idx').on(columns.updatedAt),
    index('webhook_deliveries_created_at_idx').on(columns.createdAt),
  ],
);

export const outbox_events = pgTable(
  'outbox_events',
  {
    id: serial('id').primaryKey(),
    eventType: varchar('event_type').notNull(),
    payload: jsonb('payload').notNull(),
    status: enum_outbox_events_status('status').notNull().default('pending'),
    attempts: numeric('attempts', { mode: 'number' }).notNull().default(0),
    nextAttemptAt: timestamp('next_attempt_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('outbox_events_updated_at_idx').on(columns.updatedAt),
    index('outbox_events_created_at_idx').on(columns.createdAt),
  ],
);

export const app_accepted_payments = pgTable(
  'app_accepted_payments',
  {
    id: varchar('id').primaryKey(),
    app: varchar('app_id')
      .notNull()
      .references(() => apps.id, {
        onDelete: 'set null',
      }),
    organization: varchar('organization_id')
      .notNull()
      .references(() => organizations.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    walletAddressToReceivePayment: varchar('wallet_address_to_receive_payment').notNull(),
    tokenAddress: varchar('token_address').notNull(),
    chainId: numeric('chain_id', { mode: 'number' }).notNull(),
    symbol: varchar('symbol').notNull(),
    decimals: numeric('decimals', { mode: 'number' }).notNull().default(6),
    markup: numeric('markup', { mode: 'number' }).default(0),
    discount: numeric('discount', { mode: 'number' }).default(0),
    priceFeedAddress: varchar('price_feed_address').notNull(),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('app_accepted_payments_app_idx').on(columns.app),
    index('app_accepted_payments_organization_idx').on(columns.organization),
    index('app_accepted_payments_updated_at_idx').on(columns.updatedAt),
    index('app_accepted_payments_created_at_idx').on(columns.createdAt),
  ],
);

export const app_invoices = pgTable(
  'app_invoices',
  {
    id: varchar('id').primaryKey(),
    app: varchar('app_id')
      .notNull()
      .references(() => apps.id, {
        onDelete: 'set null',
      }),
    organization: varchar('organization_id')
      .notNull()
      .references(() => organizations.id, {
        onDelete: 'set null',
      }),
    status: enum_app_invoices_status('status').notNull().default('draft'),
    baseAmount: numeric('base_amount', { mode: 'number' }).notNull(),
    totalAmount: numeric('total_amount', { mode: 'number' }).notNull(),
    currency: enum_app_invoices_currency('currency').notNull().default('USD'),
    cryptoAmountExpected: varchar('crypto_amount_expected').notNull(),
    acceptedPayment: varchar('accepted_payment_id')
      .notNull()
      .references(() => app_accepted_payments.id, {
        onDelete: 'set null',
      }),
    txHash: varchar('tx_hash'),
    originWallet: varchar('origin_wallet'),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('app_invoices_app_idx').on(columns.app),
    index('app_invoices_organization_idx').on(columns.organization),
    index('app_invoices_status_idx').on(columns.status),
    index('app_invoices_accepted_payment_idx').on(columns.acceptedPayment),
    uniqueIndex('app_invoices_tx_hash_idx').on(columns.txHash),
    index('app_invoices_updated_at_idx').on(columns.updatedAt),
    index('app_invoices_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
);

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: varchar('users_id'),
    transactionsID: integer('transactions_id'),
    appsID: varchar('apps_id'),
    'quota-usage-ledgerID': varchar('quota_usage_ledger_id'),
    organizationsID: varchar('organizations_id'),
    'organization-membersID': varchar('organization_members_id'),
    'deleted-accountsID': varchar('deleted_accounts_id'),
    'deleted-organizationsID': varchar('deleted_organizations_id'),
    'deleted-organization-membersID': varchar('deleted_organization_members_id'),
    'webhook-endpointsID': varchar('webhook_endpoints_id'),
    'webhook-deliveriesID': varchar('webhook_deliveries_id'),
    outbox_eventsID: integer('outbox_events_id'),
    'app-accepted-paymentsID': varchar('app_accepted_payments_id'),
    'app-invoicesID': varchar('app_invoices_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_transactions_id_idx').on(columns.transactionsID),
    index('payload_locked_documents_rels_apps_id_idx').on(columns.appsID),
    index('payload_locked_documents_rels_quota_usage_ledger_id_idx').on(columns['quota-usage-ledgerID']),
    index('payload_locked_documents_rels_organizations_id_idx').on(columns.organizationsID),
    index('payload_locked_documents_rels_organization_members_id_idx').on(columns['organization-membersID']),
    index('payload_locked_documents_rels_deleted_accounts_id_idx').on(columns['deleted-accountsID']),
    index('payload_locked_documents_rels_deleted_organizations_id_idx').on(columns['deleted-organizationsID']),
    index('payload_locked_documents_rels_deleted_organization_membe_idx').on(columns['deleted-organization-membersID']),
    index('payload_locked_documents_rels_webhook_endpoints_id_idx').on(columns['webhook-endpointsID']),
    index('payload_locked_documents_rels_webhook_deliveries_id_idx').on(columns['webhook-deliveriesID']),
    index('payload_locked_documents_rels_outbox_events_id_idx').on(columns.outbox_eventsID),
    index('payload_locked_documents_rels_app_accepted_payments_id_idx').on(columns['app-accepted-paymentsID']),
    index('payload_locked_documents_rels_app_invoices_id_idx').on(columns['app-invoicesID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['transactionsID']],
      foreignColumns: [transactions.id],
      name: 'payload_locked_documents_rels_transactions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['appsID']],
      foreignColumns: [apps.id],
      name: 'payload_locked_documents_rels_apps_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['quota-usage-ledgerID']],
      foreignColumns: [quota_usage_ledger.id],
      name: 'payload_locked_documents_rels_quota_usage_ledger_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['organizationsID']],
      foreignColumns: [organizations.id],
      name: 'payload_locked_documents_rels_organizations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['organization-membersID']],
      foreignColumns: [organization_members.id],
      name: 'payload_locked_documents_rels_organization_members_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['deleted-accountsID']],
      foreignColumns: [deleted_accounts.id],
      name: 'payload_locked_documents_rels_deleted_accounts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['deleted-organizationsID']],
      foreignColumns: [deleted_organizations.id],
      name: 'payload_locked_documents_rels_deleted_organizations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['deleted-organization-membersID']],
      foreignColumns: [deleted_organization_members.id],
      name: 'payload_locked_documents_rels_deleted_organization_member_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['webhook-endpointsID']],
      foreignColumns: [webhook_endpoints.id],
      name: 'payload_locked_documents_rels_webhook_endpoints_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['webhook-deliveriesID']],
      foreignColumns: [webhook_deliveries.id],
      name: 'payload_locked_documents_rels_webhook_deliveries_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['outbox_eventsID']],
      foreignColumns: [outbox_events.id],
      name: 'payload_locked_documents_rels_outbox_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['app-accepted-paymentsID']],
      foreignColumns: [app_accepted_payments.id],
      name: 'payload_locked_documents_rels_app_accepted_payments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['app-invoicesID']],
      foreignColumns: [app_invoices.id],
      name: 'payload_locked_documents_rels_app_invoices_fk',
    }).onDelete('cascade'),
  ],
);

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: varchar('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
);

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
);

export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: 'roles',
  }),
}));
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}));
export const relations_users = relations(users, ({ many }) => ({
  roles: many(users_roles, {
    relationName: 'roles',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}));
export const relations_transactions = relations(transactions, ({ one }) => ({
  owner: one(organizations, {
    fields: [transactions.owner],
    references: [organizations.id],
    relationName: 'owner',
  }),
  app: one(apps, {
    fields: [transactions.app],
    references: [apps.id],
    relationName: 'app',
  }),
  appInvoiceId: one(app_invoices, {
    fields: [transactions.appInvoiceId],
    references: [app_invoices.id],
    relationName: 'appInvoiceId',
  }),
}));
export const relations_apps_ip_whitelist = relations(apps_ip_whitelist, ({ one }) => ({
  _parentID: one(apps, {
    fields: [apps_ip_whitelist._parentID],
    references: [apps.id],
    relationName: 'ipWhitelist',
  }),
}));
export const relations_apps_domains_whitelist = relations(apps_domains_whitelist, ({ one }) => ({
  _parentID: one(apps, {
    fields: [apps_domains_whitelist._parentID],
    references: [apps.id],
    relationName: 'domainsWhitelist',
  }),
}));
export const relations_apps_rpc_configs = relations(apps_rpc_configs, ({ one }) => ({
  _parentID: one(apps, {
    fields: [apps_rpc_configs._parentID],
    references: [apps.id],
    relationName: 'rpcConfigs',
  }),
}));
export const relations_apps = relations(apps, ({ one, many }) => ({
  organization: one(organizations, {
    fields: [apps.organization],
    references: [organizations.id],
    relationName: 'organization',
  }),
  ipWhitelist: many(apps_ip_whitelist, {
    relationName: 'ipWhitelist',
  }),
  domainsWhitelist: many(apps_domains_whitelist, {
    relationName: 'domainsWhitelist',
  }),
  rpcConfigs: many(apps_rpc_configs, {
    relationName: 'rpcConfigs',
  }),
}));
export const relations_quota_usage_ledger = relations(quota_usage_ledger, ({ one }) => ({
  organization: one(organizations, {
    fields: [quota_usage_ledger.organization],
    references: [organizations.id],
    relationName: 'organization',
  }),
}));
export const relations_organizations = relations(organizations, () => ({}));
export const relations_organization_members = relations(organization_members, ({ one }) => ({
  organization: one(organizations, {
    fields: [organization_members.organization],
    references: [organizations.id],
    relationName: 'organization',
  }),
  user: one(users, {
    fields: [organization_members.user],
    references: [users.id],
    relationName: 'user',
  }),
}));
export const relations_deleted_accounts = relations(deleted_accounts, () => ({}));
export const relations_deleted_organizations = relations(deleted_organizations, () => ({}));
export const relations_deleted_organization_members = relations(deleted_organization_members, () => ({}));
export const relations_webhook_endpoints_events = relations(webhook_endpoints_events, ({ one }) => ({
  parent: one(webhook_endpoints, {
    fields: [webhook_endpoints_events.parent],
    references: [webhook_endpoints.id],
    relationName: 'events',
  }),
}));
export const relations_webhook_endpoints = relations(webhook_endpoints, ({ one, many }) => ({
  app: one(apps, {
    fields: [webhook_endpoints.app],
    references: [apps.id],
    relationName: 'app',
  }),
  events: many(webhook_endpoints_events, {
    relationName: 'events',
  }),
}));
export const relations_webhook_deliveries = relations(webhook_deliveries, ({ one }) => ({
  endpoint: one(webhook_endpoints, {
    fields: [webhook_deliveries.endpoint],
    references: [webhook_endpoints.id],
    relationName: 'endpoint',
  }),
}));
export const relations_outbox_events = relations(outbox_events, () => ({}));
export const relations_app_accepted_payments = relations(app_accepted_payments, ({ one }) => ({
  app: one(apps, {
    fields: [app_accepted_payments.app],
    references: [apps.id],
    relationName: 'app',
  }),
  organization: one(organizations, {
    fields: [app_accepted_payments.organization],
    references: [organizations.id],
    relationName: 'organization',
  }),
}));
export const relations_app_invoices = relations(app_invoices, ({ one }) => ({
  app: one(apps, {
    fields: [app_invoices.app],
    references: [apps.id],
    relationName: 'app',
  }),
  organization: one(organizations, {
    fields: [app_invoices.organization],
    references: [organizations.id],
    relationName: 'organization',
  }),
  acceptedPayment: one(app_accepted_payments, {
    fields: [app_invoices.acceptedPayment],
    references: [app_accepted_payments.id],
    relationName: 'acceptedPayment',
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
  transactionsID: one(transactions, {
    fields: [payload_locked_documents_rels.transactionsID],
    references: [transactions.id],
    relationName: 'transactions',
  }),
  appsID: one(apps, {
    fields: [payload_locked_documents_rels.appsID],
    references: [apps.id],
    relationName: 'apps',
  }),
  'quota-usage-ledgerID': one(quota_usage_ledger, {
    fields: [payload_locked_documents_rels['quota-usage-ledgerID']],
    references: [quota_usage_ledger.id],
    relationName: 'quota-usage-ledger',
  }),
  organizationsID: one(organizations, {
    fields: [payload_locked_documents_rels.organizationsID],
    references: [organizations.id],
    relationName: 'organizations',
  }),
  'organization-membersID': one(organization_members, {
    fields: [payload_locked_documents_rels['organization-membersID']],
    references: [organization_members.id],
    relationName: 'organization-members',
  }),
  'deleted-accountsID': one(deleted_accounts, {
    fields: [payload_locked_documents_rels['deleted-accountsID']],
    references: [deleted_accounts.id],
    relationName: 'deleted-accounts',
  }),
  'deleted-organizationsID': one(deleted_organizations, {
    fields: [payload_locked_documents_rels['deleted-organizationsID']],
    references: [deleted_organizations.id],
    relationName: 'deleted-organizations',
  }),
  'deleted-organization-membersID': one(deleted_organization_members, {
    fields: [payload_locked_documents_rels['deleted-organization-membersID']],
    references: [deleted_organization_members.id],
    relationName: 'deleted-organization-members',
  }),
  'webhook-endpointsID': one(webhook_endpoints, {
    fields: [payload_locked_documents_rels['webhook-endpointsID']],
    references: [webhook_endpoints.id],
    relationName: 'webhook-endpoints',
  }),
  'webhook-deliveriesID': one(webhook_deliveries, {
    fields: [payload_locked_documents_rels['webhook-deliveriesID']],
    references: [webhook_deliveries.id],
    relationName: 'webhook-deliveries',
  }),
  outbox_eventsID: one(outbox_events, {
    fields: [payload_locked_documents_rels.outbox_eventsID],
    references: [outbox_events.id],
    relationName: 'outbox_events',
  }),
  'app-accepted-paymentsID': one(app_accepted_payments, {
    fields: [payload_locked_documents_rels['app-accepted-paymentsID']],
    references: [app_accepted_payments.id],
    relationName: 'app-accepted-payments',
  }),
  'app-invoicesID': one(app_invoices, {
    fields: [payload_locked_documents_rels['app-invoicesID']],
    references: [app_invoices.id],
    relationName: 'app-invoices',
  }),
}));
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
    relationName: '_rels',
  }),
}));
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}));
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));

type DatabaseSchema = {
  enum_users_roles: typeof enum_users_roles;
  enum_transactions_adapter: typeof enum_transactions_adapter;
  enum_transactions_tracker: typeof enum_transactions_tracker;
  enum_transactions_status: typeof enum_transactions_status;
  enum_transactions_sync_status: typeof enum_transactions_sync_status;
  enum_transactions_aml_status: typeof enum_transactions_aml_status;
  enum_apps_environment: typeof enum_apps_environment;
  enum_apps_kind: typeof enum_apps_kind;
  enum_quota_usage_ledger_status: typeof enum_quota_usage_ledger_status;
  enum_organization_members_role: typeof enum_organization_members_role;
  enum_webhook_endpoints_events: typeof enum_webhook_endpoints_events;
  enum_outbox_events_status: typeof enum_outbox_events_status;
  enum_app_invoices_status: typeof enum_app_invoices_status;
  enum_app_invoices_currency: typeof enum_app_invoices_currency;
  users_roles: typeof users_roles;
  users_sessions: typeof users_sessions;
  users: typeof users;
  transactions: typeof transactions;
  apps_ip_whitelist: typeof apps_ip_whitelist;
  apps_domains_whitelist: typeof apps_domains_whitelist;
  apps_rpc_configs: typeof apps_rpc_configs;
  apps: typeof apps;
  quota_usage_ledger: typeof quota_usage_ledger;
  organizations: typeof organizations;
  organization_members: typeof organization_members;
  deleted_accounts: typeof deleted_accounts;
  deleted_organizations: typeof deleted_organizations;
  deleted_organization_members: typeof deleted_organization_members;
  webhook_endpoints_events: typeof webhook_endpoints_events;
  webhook_endpoints: typeof webhook_endpoints;
  webhook_deliveries: typeof webhook_deliveries;
  outbox_events: typeof outbox_events;
  app_accepted_payments: typeof app_accepted_payments;
  app_invoices: typeof app_invoices;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_roles: typeof relations_users_roles;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_transactions: typeof relations_transactions;
  relations_apps_ip_whitelist: typeof relations_apps_ip_whitelist;
  relations_apps_domains_whitelist: typeof relations_apps_domains_whitelist;
  relations_apps_rpc_configs: typeof relations_apps_rpc_configs;
  relations_apps: typeof relations_apps;
  relations_quota_usage_ledger: typeof relations_quota_usage_ledger;
  relations_organizations: typeof relations_organizations;
  relations_organization_members: typeof relations_organization_members;
  relations_deleted_accounts: typeof relations_deleted_accounts;
  relations_deleted_organizations: typeof relations_deleted_organizations;
  relations_deleted_organization_members: typeof relations_deleted_organization_members;
  relations_webhook_endpoints_events: typeof relations_webhook_endpoints_events;
  relations_webhook_endpoints: typeof relations_webhook_endpoints;
  relations_webhook_deliveries: typeof relations_webhook_deliveries;
  relations_outbox_events: typeof relations_outbox_events;
  relations_app_accepted_payments: typeof relations_app_accepted_payments;
  relations_app_invoices: typeof relations_app_invoices;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
