/**
 * generateAlchemyNetworksMap
 * ===========================================================================
 * Regenerates `alchemyNetworkMap.ts` (chain id → Alchemy network slug) from
 * Alchemy's public network config.
 *
 *   pnpm generate:alchemyNetworksMap
 *
 * Every reader turns a slug into `https://<slug>.g.alchemy.com/v2/<key>`, so a
 * chain missing from the map never reaches Alchemy and falls back to the other
 * RPC providers. Rerun this when Alchemy adds a network and commit the result.
 */

import { writeFileSync } from 'node:fs';
import * as path from 'node:path';

const REPO = path.resolve(import.meta.dirname, '..');

const SOURCE = 'https://app-api.alchemy.com/trpc/config.getNetworkConfig';

/** One copy per workspace package that imports the map. */
const TARGETS = [
  'apps/server/src/lib/generated/alchemyNetworkMap.ts',
];

/**
 * Each slug becomes a hostname label in front of an API key, so anything other
 * than a plain kebab-case label is refused rather than written.
 */
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function prefixWithGeneratedWarning(code: string) {
  return `// AUTOGENERATED: DO NOT MANUALLY EDIT THIS FILE\n${code}`;
}

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE} responded ${response.status} ${response.statusText}.`);

const data = (await response.json()) as {
  result?: { data?: Array<{ id: string; networkChainId?: number | null; kebabCaseId: string }> };
};

// Validated before anything is written: a changed response shape must fail
// here, not overwrite every copy with a map that has lost its networks.
const networks = data.result?.data;
if (!Array.isArray(networks) || networks.length === 0) {
  throw new Error(`${SOURCE} returned no network list; nothing was written.`);
}
const malformed = networks.find(
  (n) =>
    typeof n.kebabCaseId !== 'string' || !SLUG.test(n.kebabCaseId) || (n.networkChainId == null && typeof n.id !== 'string'),
);
if (malformed) {
  throw new Error(`${SOURCE} returned a malformed network ${JSON.stringify(malformed)}; nothing was written.`);
}

const result = networks.reduce(
  (acc, val) => {
    acc[val.networkChainId ?? val.id.replace('_', ':').toLowerCase()] = val.kebabCaseId;
    return acc;
  },
  {} as Record<number | string, string>,
);

const replacer = (key: string, value: string) => {
  if (key === 'undefined') return undefined;
  return value;
};

const code = prefixWithGeneratedWarning(
  `export const alchemyNetworkMap: Record<number | string, string> = ${JSON.stringify(result, replacer, 2).replace(/"([\d\.]+)"/g, '$1')} as const;`,
);

for (const target of TARGETS) {
  writeFileSync(path.join(REPO, target), code);
  console.log(`${target}: ${Object.keys(result).length} networks`);
}
